#!/usr/bin/env python3
"""Regenerate .claude/commands/INDEX.md from frontmatter of command .md files."""
import re
import yaml
from pathlib import Path

CMD_DIR = Path(__file__).resolve().parent.parent / ".claude" / "commands"
INDEX = CMD_DIR / "INDEX.md"


def parse_fm(text):
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    return yaml.safe_load(m.group(1)) or {} if m else {}


def fmt_list(v):
    return ", ".join(f"`{x}`" for x in v) if v else "—"


def _row_for(path):
    fm = parse_fm(path.read_text(encoding="utf-8"))
    desc_raw = fm.get("description") or ""
    desc = desc_raw.strip().splitlines()[0][:120] if desc_raw else ""
    return {
        "name": path.stem, "description": desc,
        "uses_scripts": fm.get("uses_scripts") or [],
        "dispatches": fm.get("dispatches") or [],
        "mutates_files": fm.get("mutates_files") or [],
    }


def _render(rows):
    head = [
        "# Command Index", "",
        "Auto-generated by `scripts/regen-command-index.py` from frontmatter.", "",
        "| Command | Description | uses_scripts | dispatches | mutates_files |",
        "| --- | --- | --- | --- | --- |",
    ]
    body = []
    for r in rows:
        name, desc = r["name"], r["description"]
        us, di, mf = fmt_list(r["uses_scripts"]), fmt_list(r["dispatches"]), fmt_list(r["mutates_files"])
        body.append(f"| `/{name}` | {desc} | {us} | {di} | {mf} |")
    return "\n".join(head + body) + "\n"


def main():
    rows = [_row_for(p) for p in sorted(CMD_DIR.glob("*.md")) if p.name not in ("INDEX.md", "README.md")]
    INDEX.write_text(_render(rows), encoding="utf-8")
    print(f"wrote {INDEX} ({len(rows)} commands)")


if __name__ == "__main__":
    main()
